### ISSUE TITLE
Multi-Index Query

### ISSUE THREAD

**Issue by MattTimmons** [algolia/instantsearch-core-swift#14]
Hi!
I currently use the main AlgoliaSearch swift framework and utilize the "search with multiple queries" a lot. I having difficulty quickly seeing a way to do this in this new framework. Is / could it be done?
Thanks again, and  I appreciate all the work done in this new core!
- Matt

**Comment by clement-leprovost** [comment]
Hello @MattTimmons,

What is your usage of multiple queries? Generally speaking, use cases of this feature tend to fall into two broad categories:

1. **Query aggregation:** query the same index with different parameters, or query multiple related indices (typically replicas) to aggregate their results into a more complicated result set. (This is basically what the disjunctive faceting helper does, for example.) In that case the queries are tightly related and don't make sense on their own.

2. **Query multiplexing:** issue independent queries at the same time. Here the queries are unrelated and target different indices (although they typically share the same query string). The main intended goal is usually to avoid multiple round trips to the server.

If you use case falls in the second category, i.e. you want to query different indices, but your queries are otherwise unrelated, then you can have multiple `Searcher` instances. It will even be easier to use than raw multiple queries, as you will get a different callback for each query. Don't worry about the round trip: iOS already opens multiple connections towards the server behind the scenes, and leverages HTTP pipelining, so that in practice it can even be "faster" (in elapsed response time for each query) to use individual queries. (Because they run in parallel, simply put.)

If your use case pertains to the first category, we don't support it (yet) in InstantSearch. Maybe you could tell us more about what you want to achieve; that would help us design what could become a new feature.

Last thing: we recently released **[InstantSearch iOS](https://community.algolia.com/instantsearch-ios/)**, which is a superset of InstantSearch Core specifically tailored for iOS. If you are not interested in macOS development, then you should have a look at it!

And thanks for your interest in Algolia.

**Comment by MattTimmons** [comment]
Thanks for getting back to me Clement!

Let me try to explain. And also, I would love to show you a live demo if you have some brief time to connect "offline". Would value your input.

When I wrote the app in question last year, I believe with the advice of support, they recommend three different indexes for my data structure. Without getting to specific, think of my app as a way to search for digital books.. by their title, by media assets included in the book, and most importantly, the actual text in the book.

So, we created three indexes as follows:
1. parentBooks (the book name, author, date, keywords, art, highlevel stuff)
2. bookAssets (any media assets used in all books with ID of the parentBook and url / etc).
3. bookTextExtract (the actual text chunked out in paragraphs with the ID of the parentBook).

So, when I use:

`func multipleQueries(_ queries: [IndexQuery], strategy: MultipleQueriesStrategy? = nil, completionHandler: @escaping CompletionHandler) -> Operation`

I put all three indexes in the query and then sort out the results in the completion block appropriately. If the result is not from the "parentBook" index, I then do a:

`func getObject(withID objectID: String, completionHandler: @escaping CompletionHandler) -> Operation`

to fetch the top-level info to display.

It has been working well. But, I love a lot of the efficiency of the instantSearch core (I have both an iOS and macOS app). I currently have to implement my owe logic for paging , ect.

Make sense at all?

- Matt

**Comment by clement-leprovost** [comment]
Hello @MattTimmons,

Yes, it does make sense. :) Basically you fall in use case category number 1 ("query aggregation"). Therefore using the `Seearcher` class is not that easy, because it was designed to work with a single source of data (i.e. a single index).

The good news are that it should still be possible to use it. As you may have noticed, the `Searcher` class doesn't use an `Index` directly, but a protocol called [`Searchable`](https://github.com/algolia/algoliasearch-client-swift/blob/master/Source/Searchable.swift). You can implement this protocol to send multiple queries and aggregate their results into one result set. Then you can use that implementation with the `Searcher` class.

Doing so, you may hit a few roadblocks, e.g. due to the fact that the searcher expects results to conform to a specific JSON syntax (that of the regular search responses from the API). If you do, just ping us here and we'll be happy to help! :)

The bad news are that, per se, using the `Searcher` class will *not* solve your pagination headaches, because you will still be manually aggregating multiple results sets into one. There is no built-in way in Algolia to solve this, as the logic of aggregating results is highly application-specific, and we cannot know your business logic.

Regarding the live demo, you would have to ask @spinach, who is the main developer for InstantSearch iOS (though I would still be interested in having this conversation).

**Comment by spinach** [comment]
Hey @MattTimmons, I'm pretty interested in your use case and would be happy to connect offline 🙂 . Can I contact you on the public email displayed on your GH profile matt.timmons@icloud.com?

**Comment by MattTimmons** [comment]
Yes sir!
