### ISSUE TITLE
Cannot set `facetFilters`

### ISSUE THREAD

**Issue by XiaowenVC** [algolia/instantsearch-core-swift#24]
Hello Algolia,

We need to have this information in the request: the relationship between all these `catalogLinks*` should be __OR__.
```
{
  "facetFilters": [
    [
      "catalogLinks.fr:/sacs-femme/sacs-a-main/hermes/",
      "catalogLinks.en:/sacs-femme/sacs-a-main/hermes/",
      "catalogLinks.us:/sacs-femme/sacs-a-main/hermes/",
      "catalogLinks.de:/sacs-femme/sacs-a-main/hermes/",
      "catalogLinks.it:/sacs-femme/sacs-a-main/hermes/",
      "catalogLinks.es:/sacs-femme/sacs-a-main/hermes/"
    ]
  ]
}
```
By `searcher.addFacetRefinement` it is impossible to do this.

So we should set `searcher.searchParams.facetFilters = [....]`.

But when we proceed `searcher.search()`, we found `facetFilters=[]` sent in the request. After entering the code in your SDK, we found this line. It is this line which cancels what we did by `searcher.searchParams.facetFilters = [....]`.
https://github.com/algolia/instantsearch-core-swift/blob/86ee28588934e51e0c609162275e39c6e69932cd/Sources/Searcher.swift#L384

So we would like to ask the reason why you are doing this. Or maybe it is a bug?

Thank you in advance for your reply.

**Comment by spinach** [comment]
Hey @XiaowenVC,

In order to do disjunctive faceting (OR) instead of conjunctive faceting (AND), you can use `setFacet(withName:disjunctive:).`

From our [community website for InstantSearch Core](https://community.algolia.com/instantsearch-core-swift/guide/search.html) in the filtering section:

> A given facet can be treated as either conjunctive (the default—refinements combined with an AND operator) or disjunctive (refinements combined with an OR). You can modify the conjunctive/disjunctive status of a facet by calling setFacet(withName:disjunctive:).

**Comment by XiaowenVC** [comment]
Hi @spinach,

Thank you for the rapid response, but marking the facet as disjunctive does NOT resolve the problem.

I will take a short example to explain how __disjunctive__ do the relation OR, in Swift, I do:
```
let catalogLangs = ["fr", "en", "de"]
catalogLangs.forEach {
	searcher.params.setFacet(withName: "link.\($0)", disjunctive: true)
	searcher.params.addFacetRefinement(name: "link.\($0)", value: "A")
	searcher.params.addFacetRefinement(name: "link.\($0)", value: "B")
}
```
Then the SDK translates:
```
.....
&facetFilters=[
  [
    "link.en:A",
    "link.en:B"
  ],
  [
    "link.de:A",
    "link.de:B"
  ],
  [
    "link.fr:A",
    "link.fr:B"
  ]
]&.......
```
which means
```
(link.en:A OR link.en:B) AND (link.de:A, link.de:B) AND (link.fr:A, link.fr:B)
```
c.f. syntax of facetFilters https://www.algolia.com/doc/api-reference/api-parameters/facetFilters/
and conclusion: `setFacet(withName:disjunctive:)` only do the disjunction between different values under the __SAME__ key.

But for my case, I need the disjunction of __DIFFERENT__ keys, example:
```
link.fr:A OR link.en:A OR link.de:A
```
which translates in facetFilters like:
```
[
    [
      "link.en:A",
      "link.fr:A",
      "link.de:A"
    ]
]
```

There's nothing in InstantSearchCore I can find which does this work. So I have to write it manually and directly in `facetFilters` key.

So I will reformulate my question, without entering in details of your code:
I use `Searcher` class from InstantSearchCore to do my searches via Algolia, with this class, how can I do what I mentioned above?

**Comment by spinach** [comment]
Ohh I see @XiaowenVC thanks a lot for describing in detail all of this. Will look into it to see what's the best way to get this done

**Comment by spinach** [comment]
Hey @XiaowenVC,

After further investigation, you are right that we're actually lacking this feature in our library. It is not possible to achieve it with the InstantSearch Core library by itself and it is a limitation that we should fix. 

A couple of points:

1- The `facetFilters` parameters is actually not nil. The way disjunctive faceting works is that if we have N disjunctive facets with X conjunctive facets, then we usually do N requests to our servers in order to get the results (the request consisting of each disjunctive facet with the X conjunctive facets). If you put a breakpoint [at this level](https://github.com/algolia/algoliasearch-client-swift/blob/cf2f7b4b7dc1f9c9e8c6b893dd21ffae6a303303/Sources/AlgoliaSearch-Client/Helpers/DisjunctiveFaceting.swift#L60) then you will be able to see how the facetFilters get filled for each iteration. 

2- Your case is a bit different since you only want OR operations and have no AND operations, so you can do it with 1 request by just using facetFilters exactly as you mentioned. However you will have to use our API client in order to do it, specifically the [index.search](https://github.com/algolia/algoliasearch-client-swift/blob/master/Sources/AlgoliaSearch-Client/Index.swift#L358) method. You will have to take care of filling in the `Query` parameter with `facetFilters` and other fields. For a quick tutorial on how to use the API client, check this [here](https://www.algolia.com/doc/tutorials/search-ui/instant-search/build-an-instant-search-results-page/swift/?language=swift#search-logic)

Thanks for detecting this and I'll let you know as soon as we add this functionality to InstantSearch Core.

**Comment by spinach** [comment]
yep sure https://github.com/algolia/instantsearch-android/issues/81

**Comment by spinach** [comment]
Hey @XiaowenVC,

It seems Instantsearch.js has the same functionality: only doing disjunctive faceting over a single facet. I am curious what kind of UI would it look like? I think it's the first time we get this feature request, that's why we didn't have it. If you can share more about the use case it would be great! cc @bobylito

**Comment by XiaowenVC** [comment]
The UI is nothing special, it is just a list of product.
Before describing the use case, I will explain the context:
We have all our products in an index Algolia, each product is associated with multiple links, and these links are translated in multiple languages (for the need of our web, to show a translated readable url in address bar). 
So when we query Algolia with a link, we can get all products containing this link, it's by this way that we get a product list of certain category/brand/....
For example, this [product](http://vst.re/p5792687) has these links:
```
"catalogLinks": {
        "fr": [
	  ......
          "/sacs-femme/sacs-a-main/hermes/",
	  ......
        ],
        "en": [
	  ......
          "/women-bags/handbags/hermes/",
	  ......
        ],
        "de": [
	  ......
          "/damen-taschen/handtaschen/hermes/",
	  ......
        ],
	......
}
```
Which means we can see this product by in urls of these 3 languages:
http://www.vestiairecollective.com/sacs-femme/sacs-a-main/hermes/
http://www.vestiairecollective.com/women-bags/handbags/hermes/
http://www.vestiairecollective.com/damen-taschen/handtaschen/hermes/

For our mobile app, in order to show a product list, we also query Algolia with a link.
In many cases, for example by a deeplink `com.vestiairecollective.vestiaire://action?type=catalogue&link=/sacs-femme/sacs-a-main/hermes/`, we cannot know in which language the link is, so we should query Algolia with a query which means:
I want all products with `catalogLinks.fr:/sacs-femme/sacs-a-main/hermes/ OR catalogLinks.en:/sacs-femme/sacs-a-main/hermes/ OR .....`.

For instant search, I think it is difficult to cover all use cases by creating different xxxRefinement methods. But all clients can have different needs. I have a suggestion:
In instant search, give clients the possibility to write manually their queries for `filters`, `numericFilters`, `facetFilters`, etc. Then the SDK should merge these manual queries with its auto-built queries.

**Comment by spinach** [comment]
Okay makes sense, I see the use case! I will discuss with the team to see what's the best way to surface this. Thanks for the suggestions!

**Comment by zgosalvez** [comment]
@spinach It's been 4 months; Any update on this from the team? I have a related issue #33.

**Comment by spinach** [comment]
The new version of InstantSearch solves this with `FilterState` which is flexible and should cover all use cases.
