### ISSUE TITLE
Add specific "InstantSearch-core swift" user agent for analytics

### ISSUE THREAD

**Issue by vvo** [algolia/instantsearch-core-swift#5]
To be able to track down usages we should query the Algolia API with a specific agent, much like https://github.com/algolia/instantsearch-android/blob/e3e8a43eed56db8448c6de2f77ec3604a6b76ab9/instantsearch/src/main/java/com/algolia/instantsearch/helpers/Searcher.java#L73

What do you think?

**Comment by clement-leprovost** [comment]
It's [already the case](https://github.com/algolia/instantsearch-core-swift/blob/master/Sources/Searcher.swift#L239-L248). The code is not obvious because it relies on reflection to get the library name, but an application using InstantSearch Core for Swift will send a `User-Agent` HTTP header similar to the following:

```
Algolia for Swift (4.5.0); iOS (10.2); InstantSearchCore (1.0.0)
```

This follows our current API Client Specification (as far as I understand it). @vvo Is that OK or would you like an alternative value?

**Comment by vvo** [comment]
No 100% OK, I searched for the code bits in the lib but could not find it. Thanks!
